import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Manual sidebar — curated order and grouping, not filesystem-autogenerated.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'overview',
    'getting-started',
    'features',
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: ['architecture', 'api-integration', 'edge-cases'],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: false,
      items: ['tech-stack', 'deployment'],
    },
    'decisions',
  ],
};

export default sidebars;
